association/config/routes.rb
Association::Application.routes.draw do
  resources :residential_halls

  resources :students
  match '/about' => 'students#about'

end

association/app/models/residential_hall.rb
class ResidentialHall < ActiveRecord::Base
  attr_accessible :block_name, :capacity, :date_of_opening, :hall_number
  has_many :students, dependent: :destroy
end

association/app/models/student.rb
class Student < ActiveRecord::Base
  attr_accessible :address, :age, :contact_number, :m_number, :name,
                  :period_of_stay, :registration_date, :sex, :date_of_birth,
                  :residential_hall_id, :hall_number
  belongs_to :residential_hall

  validates :address, presence: true
  validates :age, presence: true
  validates :contact_number, presence: true, length: { is: 10, message: 'is of wrong length' }
  validates :m_number, presence: true
  validates :name, presence: true
  validates :sex, presence: true
  validates :date_of_birth, presence: true
  validates :residential_hall_id, presence: true
end

association/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

association/app/controllers/residential_halls_controller.rb
class ResidentialHallsController < ApplicationController
  # GET /residential_halls
  # GET /residential_halls.json
  def index
    @residential_halls = ResidentialHall.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @residential_halls }
    end
  end

  # GET /residential_halls/1
  # GET /residential_halls/1.json
  def show
    @residential_hall = ResidentialHall.find(params[:id])
    respond_to do |format|
      format.html {render "students/index", :locals => { student: @residential_hall.students }}# show.html.erb
    end
  end

  # GET /residential_halls/new
  # GET /residential_halls/new.json
  def new
    @residential_hall = ResidentialHall.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @residential_hall }
    end
  end

  # GET /residential_halls/1/edit
  def edit
    @residential_hall = ResidentialHall.find(params[:id])
  end

  # POST /residential_halls
  # POST /residential_halls.json
  def create
    @residential_hall = ResidentialHall.new(params[:residential_hall])

    respond_to do |format|
      if @residential_hall.save
        format.html { render 'residential_halls/show', locals: {residential_hall: @residential_hall}, notice: 'Residential hall was successfully created.' }
        format.json { render json: @residential_hall, status: :created, location: @residential_hall }
      else
        format.html { render action: "new" }
        format.json { render json: @residential_hall.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /residential_halls/1
  # PUT /residential_halls/1.json
  def update
    @residential_hall = ResidentialHall.find(params[:id])

    respond_to do |format|
      if @residential_hall.update_attributes(params[:residential_hall])
        format.html {  render 'residential_halls/show', locals: {residential_hall: @residential_hall}, notice: 'Residential hall was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @residential_hall.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /residential_halls/1
  # DELETE /residential_halls/1.json
  def destroy
    @residential_hall = ResidentialHall.find(params[:id])
    @residential_hall.destroy

    respond_to do |format|
      format.html { redirect_to residential_halls_url }
      format.json { head :no_content }
    end
  end
end

association/app/controllers/students_controller.rb
class StudentsController < ApplicationController
  # GET /students
  # GET /students.json
  def index
    @students = Student.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @students }
    end
  end

  # GET /students/1
  # GET /students/1.json
  def show
    @student = Student.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @student }
    end
  end

  # GET /students/new
  # GET /students/new.json
  def new
    @student = Student.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @student }
    end
  end

  # GET /students/1/edit
  def edit
    @student = Student.find(params[:id])
  end

  # POST /students
  # POST /students.json
  def create
    residential_hall = ResidentialHall.find_by_hall_number(params[:student][:hall_number])
    @student = residential_hall.students.build(params[:student])

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render json: @student, status: :created, location: @student }
      else
        format.html { render action: "new" }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /students/1
  # PUT /students/1.json
  def update
    @student = Student.find(params[:id])

    respond_to do |format|
      if @student.update_attributes(params[:student])
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student = Student.find(params[:id])
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url }
      format.json { head :no_content }
    end
  end
end

association/app/helpers/application_helper.rb
module ApplicationHelper
end

association/app/helpers/residential_halls_helper.rb
module ResidentialHallsHelper
end

association/app/helpers/students_helper.rb
module StudentsHelper
end

association/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Residential Hall has many students relationship</title>
<%= stylesheet_link_tag "application", media: "all" %>
<%= javascript_include_tag "application" %>
<%= csrf_meta_tags %>
</head>
<body class="<%= controller.controller_name %>">
<div id="banner">
<%= "Residential Hall has many students relationship" %>
<div id="about">
<%= link_to 'About', about_path %>
</div>
</div>
<div id="main">
<%= yield %>
</div>
</body>
</html>

association/app/views/residential_halls/_form.html.erb
<%= form_for(@residential_hall) do |f| %>
  <% if @residential_hall.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@residential_hall.errors.count, "error") %> prohibited this residential_hall from being saved:</h2>

      <ul>
      <% @residential_hall.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :hall_number %><br />
    <%= f.number_field :hall_number %>
  </div>
  <div class="field">
    <%= f.label :capacity %><br />
    <%= f.number_field :capacity %>
  </div>
  <div class="field">
    <%= f.label :block_name %><br />
    <%= f.text_field :block_name %>
  </div>
  <div class="field">
    <%= f.label :date_of_opening %><br />
    <%= f.date_select :date_of_opening %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

association/app/views/residential_halls/edit.html.erb
<h1>Editing residential_hall</h1>

<%= render 'form' %>

<%= link_to 'Back', residential_halls_path %>

association/app/views/residential_halls/index.html.erb
<h1>Residential Halls</h1>

<table>
  <tr>
    <th>Hall number</th>
    <th>Capacity</th>
    <th>Block name</th>
    <th>Date of opening</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @residential_halls.each do |residential_hall| %>
  <tr>
    <td><%= residential_hall.hall_number %></td>
    <td><%= residential_hall.capacity %></td>
    <td><%= residential_hall.block_name %></td>
    <td><%= residential_hall.date_of_opening %></td>
    <td><%= link_to 'Show', residential_hall %></td>
    <td><%= link_to 'Edit', edit_residential_hall_path(residential_hall) %></td>
    <td><%= link_to 'Destroy', residential_hall, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Residential hall', new_residential_hall_path %>
<%= link_to 'View List of all students', students_path %>

association/app/views/residential_halls/new.html.erb
<h1>New residential_hall</h1>

<%= render 'form' %>

<%= link_to 'Back', residential_halls_path %>

association/app/views/residential_halls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Hall number:</b>
  <%= residential_hall.hall_number %>
</p>

<p>
  <b>Capacity:</b>
  <%= residential_hall.capacity %>
</p>

<p>
  <b>Block name:</b>
  <%= residential_hall.block_name %>
</p>

<p>
  <b>Date of opening:</b>
  <%= residential_hall.date_of_opening %>
</p>


<%= link_to 'Edit', edit_residential_hall_path(residential_hall) %> |
<%= link_to 'Back', residential_halls_path %>

association/app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :m_number %><br />
    <%= f.number_field :m_number %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, required: true %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_area :address,  rows: 6 %>
  </div>
  <div class="field">
    <%= f.label :age %><br />
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :sex %><br />
    <%= f.text_field :sex %>
  </div>
  <div class="field">
    <%= f.label :date_of_birth %><br />
    <%= f.date_select :date_of_birth, end_year: DateTime.now.year - 50 %>
  </div>
  <div class="field">
    <%= f.label :registration_date %><br />
    <%= f.date_select :registration_date %>
  </div>
  <div class="field">
    <%= f.label :period_of_stay %><br />
    <%= f.number_field :period_of_stay %>
  </div>
  <div class="field">
    <%= f.label :contact_number %><br />
    <%= f.number_field :contact_number %>
  </div>
    <div class="field">
    <%= f.label :hall_number %><br />
    <%= f.number_field :hall_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

association/app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

association/app/views/students/index.html.erb
<% if params[:controller] == 'residential_halls' %>
  <% @students = student %>
<% end  %>
<h1>Listing students</h1>

<table>
  <tr>
    <th>M number</th>
    <th>Name</th>
    <th>Address</th>
    <th>Age</th>
    <th>Sex</th>
    <th>Date Of Birth</th>
    <th>Registration date</th>
    <th>Period of stay(In months)</th>
    <th>Contact number</th>
    <th>Residential Hall number</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @students.each do |student| %>
  <tr>
    <td><%= student.m_number %></td>
    <td><%= student.name %></td>
    <td><%= student.address %></td>
    <td><%= student.age %></td>
    <td><%= student.sex %></td>
    <td><%= student.date_of_birth %></td>
    <td><%= student.registration_date %></td>
    <td><%= student.period_of_stay %></td>
    <td><%= student.contact_number %></td>
    <td><%= student.hall_number %></td>
    <td><%= link_to 'Show', student %></td>
    <td><%= link_to 'Edit', edit_student_path(student) %></td>
    <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Student', new_student_path %>
<%= link_to 'View Residential Halls List', residential_halls_path%>

association/app/views/students/new.html.erb
<h1>New student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

association/app/views/students/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <b>M number:</b>
  <%= @student.m_number %>
</p>

<p>
  <b>Name:</b>
  <%= @student.name %>
</p>

<p>
  <b>Address:</b>
  <%= @student.address %>
</p>

<p>
  <b>Age:</b>
  <%= @student.age %>
</p>

<p>
  <b>Sex:</b>
  <%= @student.sex %>
</p>

<p>
  <b>Date Of Birth:</b>
  <%= @student.date_of_birth   %>
</p>

<p>
  <b>Registration date:</b>
  <%= @student.registration_date %>
</p>

<p>
  <b>Period of stay:</b>
  <%= @student.period_of_stay %>
</p>

<p>
  <b>Contact number:</b>
  <%= @student.contact_number %>
</p>

<p>
  <b>Residential Hall number:</b>
  <%= @student.hall_number %>
</p>


<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>